### ISSUE TITLE
clue numbering is unexpected

### ISSUE THREAD

**Issue by raisjn** [sandsmark/recrossable#4]
the numbering of clues in the crossword is not the usual expected numbering of clues. 

in the couple crosswords i tried, the numbering started in the bottom right and increased upwards. in a normal crossword, the numbering starts in the top left and increases from left to right.

**Comment by sandsmark** [comment]
I'll admit I don't really do crosswords much, and the UI here was just "designed" by easy it could be done.

but unless I'm misunderstanding something, how it looks here is correct, isn't it?:
![image](https://user-images.githubusercontent.com/25765/95480985-05a18c00-097c-11eb-8445-7688ff074108.png)

I should probably have switched the down and across, though, since making the "down" hints go down and vice versa makes more sense.

**Comment by raisjn** [comment]
this does not look correct. the upper left should be clue 1, then the next clue would be the next across word to the right and labeled 2 and so on.

can look at nyt crossword to see what i mean

edit: the numbering of the cells is what i am referring to

**Comment by sandsmark** [comment]
ah, that makes more sense, that numbering is very arbitrary

I'll see if I get around to fixing it some day

**Comment by raisjn** [comment]
https://github.com/sandsmark/recrossable/pull/10 addresses this

**Comment by sandsmark** [comment]
I assume I can close this now that #10 is merged.
